version: "3.4"
services:
  rabbitmq:
    container_name: rabbitmq
    image: "rabbitmq:3-alpine"
    ports:
      - "5672"
    restart: unless-stopped
  heimdalld:
    build: &ref_0
      args:
        UPSTREAM_VERSION: v0.2.4
      context: ./build/heimdall
      dockerfile: Dockerfile
    volumes:
      - "heimdall:/root/.heimdalld"
    ports:
      - "36656:26656"
      - "36657:26657"
    depends_on:
      - rabbitmq
    environment:
      - MONIKER=DAPPNodler
      - >-
        SNAPSHOT_URL=https://matic-blockchain-snapshots.s3-accelerate.amazonaws.com/matic-mumbai/heimdall-snapshot-2021-12-09.tar.gz
      - BOOTSTRAP=1
      - "ETH1_RPC_URL=http://fullnode.dappnode:8545"
    restart: unless-stopped
    image: "heimdalld.polygon-mumbai.public.dappnode.eth:0.1.4"
  heimdallr:
    environment:
      - REST_SERVER=1
      - "ETH1_RPC_URL=http://fullnode.dappnode:8545"
    build: *ref_0
    volumes:
      - "heimdall:/root/.heimdalld"
    ports:
      - "1317"
    depends_on:
      - heimdalld
    restart: unless-stopped
    image: "heimdallr.polygon-mumbai.public.dappnode.eth:0.1.4"
  bor:
    build:
      args:
        UPSTREAM_VERSION: v0.2.12-candidate
      context: ./build/bor
      dockerfile: Dockerfile
    hostname: bor
    environment:
      - >-
        SNAPSHOT_URL=https://matic-blockchain-snapshots.s3-accelerate.amazonaws.com/matic-mumbai/bor-fullnode-snapshot-2021-12-20.tar.gz
      - BOOTSTRAP=1
    volumes:
      - "bor:/datadir"
    ports:
      - "10545:8545"
      - "10546:8546"
      - "40303:30303"
      - "40303:30303/udp"
    depends_on:
      - heimdallr
    restart: unless-stopped
    image: "bor.polygon-mumbai.public.dappnode.eth:0.1.4"
  nginx:
    build:
      context: ./build/nginx
      dockerfile: Dockerfile
    environment:
      - INT_HTTP=8545
      - EXT_HTTP=10645
      - INT_WS=8546
      - EXT_WS=10646
      - AUTH_USER=admin
      - AUTH_PASSWORD=12345
      - WS_NAME=bor
    ports:
      - "10645:10645"
      - "10646:10646"
    depends_on:
      - bor
    restart: unless-stopped
    image: "nginx.polygon-mumbai.public.dappnode.eth:0.1.4"
volumes:
  heimdall: {}
  bor: {}
